### ISSUE TITLE
Wiki is incomplete

### ISSUE THREAD

**Issue by afilich** [hottera/Food_Savior_Website#9]
Since our Wiki page is mostly empty we should make sure that all parts of it are completed till the end of the day.

**Comment by baderas2000** [comment]
* Complete and check wiki information
* Complete pm experience info

**Comment by baderas2000** [comment]
* correction of stylistic and grammatical mistakes

**Comment by hottera** [comment]
habe unseren code - wie in der E-Mail gefordert in den Reiter - Code/ Enviroment verschoben.

Habe zwei sub isuess erstellt - für kanban tablle und unserer pm experience - schreibe für zweiteres eine erweiterung welche, z.B. die Frage beinhaltet warum wir soviele issues aber sowenig kommentare haben

**Comment by hottera** [comment]
Habe Kanban etwas geupdatet sodass etwas mehr unserer erfahrung damit entspricht (also das wir hauptsächlich die onboard autmatische funktion benutzt haben)

Weiters habe ich unseren PM expirience Beitrag um einen punkt erweitert der erklärt warum wir so viele issues haben welche dann keine weiteren kommentare haben und einfach im "done" breich gelandet sind

**Comment by hottera** [comment]
Hallo leute - wir haben das wiki nochmals etws überarbeitet - vor allem die punkte unter unserer pm experience wurde nochmals geupdatet - bitte um ein kurzes feedback was wir davon haltet.

Meiner meinung nach wäre sonst unser wiki soweit fertig. 
LG

**Comment by baderas2000** [comment]
I think it’s great that we analyzed and described the difficulties('barriers') during the work process more detailed

**Comment by afilich** [comment]
> Hallo leute - wir haben das wiki nochmals etws überarbeitet - vor allem die punkte unter unserer pm experience wurde nochmals geupdatet - bitte um ein kurzes feedback was wir davon haltet.
> 
> Meiner meinung nach wäre sonst unser wiki soweit fertig.
> LG

Jetzt schaut's definitiv besser als unsere letzte Version aus, könntest den Issue schließen.

**Comment by hottera** [comment]
Ok leute vielen dank fürs feedback ich lege den issue also dann zu den akten =)
